# Generated by Django 4.2.2 on 2023-07-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
