# Generated by Django 4.2.4 on 2023-08-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ticket_message_messageindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='messageIndex',
        ),
    ]
